FROM python:3.8

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    libpq-dev \
    && pip install --upgrade pip \
    && pip install rasa==3.5.17 rasa-sdk==3.5.17

CMD ["rasa", "run", "--enable-api", "--cors", "*", "--endpoints", "endpoints.yml"]