FROM python:3.8-slim

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    && pip install --upgrade pip \
    && pip install rasa-sdk==3.6.2

CMD ["rasa", "run", "actions"]